E2e automation
unagatacuriosa/AutomationApiPetsStore pull request #1
Opened 2023-06-01 14:16 UTC by unagatacuriosa

2023-06-02 06:10 UTC, ramonlr93 requested changes
Revisa los comentarios que te he dejado sobre el código, cuando lo tengas modificado, vuelves a subir los cambios y te daré el approve para poder hacer merge

2023-06-02 06:10 UTC, ramonlr93 commented on src/test/java/com/cucumber/stepdefs/StoreImplementations.java
> +    public void returnsOkRemovePurchasing(int arg0) {
EL parámetro arg0 no lo usas en ningún sitio, sobraría, igual que en el gherkin el {int}

2023-06-02 06:10 UTC, ramonlr93 commented on src/test/java/com/cucumber/stepdefs/StoreImplementations.java
> +        storeResponse = given().contentType(ContentType.JSON).body(file).post("https://petstore.swagger.io/v2/store/order");
La uri base de la petición deberías tenerla en un before, ya que se repite para todas las peticiones https://petstore.swagger.io/v2

2023-06-02 06:10 UTC, ramonlr93 commented on src/test/java/com/cucumber/stepdefs/UserImplementations.java
> +    public void returnsOkAndCreateUser(int arg0) {
EL parámetro arg0 no lo usas en ningún sitio, sobraría, igual que en el gherkin el {int}

2023-06-02 06:10 UTC, ramonlr93 commented on src/test/java/com/cucumber/stepdefs/UserImplementations.java
> +    public void returnsAndValidateTheUsername(int arg0) {
EL parámetro arg0 no lo usas en ningún sitio, sobraría, igual que en el gherkin el {int}

2023-06-02 06:10 UTC, ramonlr93 commented on src/test/java/com/cucumber/stepdefs/UserImplementations.java
> +    @Then("returns {int} remove user")
EL parámetro arg0 no lo usas en ningún sitio, sobraría, igual que en el gherkin el {int}

2023-06-06 15:49 UTC, ramonlr93 approved these changes
Ahora mejor, práctica correcta ya podrías hacer merge

2023-06-06 23:53 UTC, unagatacuriosa commented
Ya están subidos, no me llegó la notificación al correo y me enteré tarde de tus comentarios

2023-06-07 07:10 UTC, merged